input:
  grid_path: "data/raw/indonesia_tiles.geojson"
  modifications_path: "data/raw/empty_modifications.geojson"
  geomorphology_path: "https://s3.ap-southeast-2.amazonaws.com/files.auspatious.com/coastlines/coastal_geomorphology.zip"

output:
  location: "data/processed/"
  crs: "EPSG:32651"

stac:
  stac_api_url: "https://landsatlook.usgs.gov/stac-server"
  stac_collections:
    - "landsat-c2l2-sr"
  lower_scene_limit: 250
  upper_scene_limit: 2000

options:
  start_year: 2020
  end_year: 2023
  baseline_year: 2021

  water_index: "mndwi_nir"
  index_threshold: 0.65

  mask_with_hillshade: True
  mask_with_esa_wc: True

  load_buffer_distance: 5000

aws:
  aws_unsigned: False
  aws_request_payer: True