input:
  grid_path: "https://raw.githubusercontent.com/auspatious/coastlines/main/data/raw/indonesia_tiles.geojson"
  modifications_path: "https://raw.githubusercontent.com/auspatious/coastlines/main/data/raw/empty_modifications.geojson"
  geomorphology_path: "https://s3.ap-southeast-2.amazonaws.com/files.auspatious.com/coastlines/coastal_geomorphology.zip"

output:
  location: "s3://easi-asia-dc-data-projects/coastlines/indo/"
  crs: "EPSG:32651"

stac:
  stac_api_url: "https://landsatlook.usgs.gov/stac-server"
  stac_collections:
    - "landsat-c2l2-sr"
  lower_scene_limit: 250
  upper_scene_limit: 2000

options:
  start_year: 1980
  end_year: 2023
  baseline_year: 2021

  tide_model: "ensemble"

  water_index: "mndwi_nir"
  index_threshold: 0.65

  mask_with_hillshade: True
  hillshade_stac_catalog: "https://earth-search.aws.element84.com/v1"
  hillshade:_stac_collection: "cop-dem-glo-30"
  
  use_ensemble: True
  ensemble_model_list: 
    - "FES2014"
    - "FES2022"
    - "EOT20"
    - "TPXO9-atlas-v5-nc"
    - "TPXO10-atlas-v2-nc"
    - "GOT5.6"
  ensemble_model_rankings: "https://files.auspatious.com/coastlines/indo_model_rankings.fgb"

  mask_with_esa_wc: True

  load_buffer_distance: 5000

aws:
  aws_unsigned: False
  aws_request_payer: True
