input:
  grid_path: "https://raw.githubusercontent.com/auspatious/coastlines/main/data/raw/indonesia_tiles.geojson"
  organisation: "big"
  collection_url: "https://stac.auspatious.com/collections"

output:
  location: "s3://easi-asia-dc-data-projects/coastlines" 
  crs: "EPSG:32651"

stac:
  stac_api_url: "https://earth-search.aws.element84.com/v1"
  stac_collections:
    ls: "landsat-c2-l2"
    s2: "sentinel-2-l2a"

options:
  start_year: 2022
  end_year: 2024
  label_year: 2023

  tide_model: "ensemble"
  use_ensemble: True
  ensemble_model_list: 
    - "FES2014"
    - "FES2022"
    - "EOT20"
    - "TPXO9-atlas-v5-nc"
    - "TPXO10-atlas-v2-nc"
    - "GOT5.6"
  ensemble_model_rankings: "https://files.auspatious.com/coastlines/indo_model_rank.fgb"

  use_exposure_offsets: True
  modelled_freq: 3h

  use_https_href_links: False

aws:
  aws_unsigned: False
  aws_request_payer: True
