Input files:
    grid_path: data/raw/vietnam_tiles.geojson
    modifications_path: data/raw/vietnam_modifications.geojson
STAC config:
    stac_api_url: "https://landsatlook.usgs.gov/stac-server"
    stac_collections: 
        - "landsat-c2l2-sr"
    lower_scene_limit: 200
    upper_scene_limit: 3000
