Input files:
    grid_path: https://raw.githubusercontent.com/auspatious/dea-coastlines/stable/data/raw/vietnam_tiles.geojson
    modifications_path: https://raw.githubusercontent.com/auspatious/dea-coastlines/stable/data/raw/vietnam_modifications.geojson
    geomorphology_path: https://s3.ap-southeast-2.amazonaws.com/files.auspatious.com/coastlines/coastal_geomorphology.zip
STAC config:
    stac_api_url: "https://landsatlook.usgs.gov/stac-server"
    stac_collections: 
        - "landsat-c2l2-sr"
    lower_scene_limit: 200
    upper_scene_limit: 2500
